import React, { Fragment } from "react";
import Button from "@material-ui/core/Button";
import Dialog from "@material-ui/core/Dialog";
import DialogActions from "@material-ui/core/DialogActions";
import DialogTitle from "@material-ui/core/DialogTitle";
import {
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Autocomplete,
} from "@mui/material";
import AsyncCSV from "./AsyncCSV";
import CourseDropDown from "./CourseDropDown";
import {
  collection,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  FieldValue,
  query,
  limit,
  orderBy,
  startAfter,
  startAt,
  endBefore,
  limitToLast,
  setState,
  where,
} from "firebase/firestore";
import { db } from "../firebase-config";
import CircularProgress from "@mui/material/CircularProgress";
import FirebaseForm from "./FirebaseForm";

export default function AlertDialog(props) {
  const [open, setOpen] = React.useState(false);
  // const loading = open && courseList.length === 0;

  let handleClickOpen = async () => {
    setOpen(true);
    // Only generate course list when opened
    // setCourseList(await getCourseList());
    // console.log(courseList);
  };

  function handleClose() {
    setOpen(false);
  }

  let queries = {
    userID: null,
    courseName: null,
    courseID: null,
  };

  // Contains multiple types depending on passed in prop
  return (
    <div>
      {props.type === "csvExport" && (
        <Fragment>
          <Button variant="outlined" color="primary" onClick={handleClickOpen}>
            Export to CSV
          </Button>

          <Dialog
            open={open}
            onClose={handleClose}
            aria-labelledby="alert-dialog-title"
            aria-describedby="alert-dialog-description"
          >
            <DialogTitle id="alert-dialog-title">
              {"Optional Queries"}
            </DialogTitle>

            <DialogActions>
              <TextField
                id="outlined-basic"
                label="User ID"
                variant="outlined"
                onChange={(e) => {
                  queries.userID = e.target.value;
                }}
              />
              {/* Wait for props before rendering */}
              {/* CourseList generated by button click to open dialog box */}
              {/* Empty array is true, check length */}
              {/* {courseList.length ? ( */}
                <CourseDropDown/>
              {/* ) : null} */}

              <Button onClick={handleClose} color="primary" autoFocus>
                Close
              </Button>

              <AsyncCSV queries={queries} />
            </DialogActions>
          </Dialog>
        </Fragment>
      )}

      {props.type === "courseEntry" && (
        <Fragment>
          <Button variant="outlined" color="primary" onClick={handleClickOpen}>
            Add Course
          </Button>

          <Dialog
            open={open}
            onClose={handleClose}
            aria-labelledby="alert-dialog-title"
            aria-describedby="alert-dialog-description"
          >
            <DialogTitle id="alert-dialog-title">{"Add Course"}</DialogTitle>

            <DialogActions>
              <FirebaseForm formType="courseEntry" collectionName="courses" />

              <Button onClick={handleClose} color="primary" autoFocus>
                Close
              </Button>
            </DialogActions>
          </Dialog>
        </Fragment>
      )}
    </div>
  );
}
